title: OnDevs
baseURL: /
params:
  palette: cyan
  base_font: nunito-sans
  header:
    type: header
    template: header
    logo_img: /images/OD.png
    logo_img_alt: OnDevs
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Services
        url: /features
        style: link
        has_icon: true
        icon: arrow-right
      - type: action
        template: action
        label: Pricing
        url: /pricing
        style: link
        icon: arrow-right
        has_icon: true
      - type: action
        template: action
        label: Contact
        url: /contact
        style: primary
        has_icon: true
        icon: envelope
      - label: lorem-ipsum
        url: lorem-ipsum
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
  footer:
    type: footer
    template: footer
    sections:
      - type: footer_text
        template: footer_text
        image: /images/blue-celery.png
        image_alt: Footer logo
        image_url: /
        content: 'OnDevs, because business never stops'
      - type: footer_nav
        template: footer_nav
        title: Company
        nav_links:
          - type: action
            template: action
            label: About Us
            url: /about
            style: link
          - type: action
            template: action
            label: Blog
            url: /blog
            style: link
          - type: action
            template: action
            label: Sign Up
            url: /signup
            style: link
          - type: action
            template: action
            label: Contact
            url: /contact
            style: link
      - type: footer_nav
        template: footer_nav
        title: Community
        nav_links:
          - type: action
            template: action
            label: Twitter
            url: 'https://twitter.com/'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - type: action
            template: action
            label: LinkedIn
            url: 'https://www.linkedin.com/'
            style: link
            has_icon: true
            icon: linkedin
            icon_position: left
          - type: action
            template: action
            label: GitHub
            url: 'https://github.com/'
            style: link
            has_icon: true
            icon: github
            icon_position: left
      - type: footer_form
        template: footer_form
        title: Subscribe
        content: Stay up to date with our latest developments.
        form_id: contactForm
        hide_labels: true
        form_fields:
          - type: form_field
            template: form_field
            input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Terms of Service
        url: /terms-of-service
        style: link
      - type: action
        template: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    content: "Static site created by\_OnDevs. All rights reserved."
  domain: ondevs.com
  favicon: /images/magical-sun.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
